language: fortran

git:
   depth: 1

env:
  - FDICT_OPT=0
  - FDICT_OPT=3

matrix:
   include:
     - os: linux
       sudo: required
     - os: osx
   exclude:
     - os: osx
       env: FDICT_OPT=3

notifications:
   email:
      recipients:
         - nickpapior@gmail.com
      on_failure: always
      on_success: change

before_install:
   - .travis/before_install.sh

install:
   - .travis/install.sh

script:
   - .travis/script.sh
