language: fortran

os:
   - linux
   - macosx

notifications:
   email:
      recipients:
         - nickpapior@gmail.com
      on_failure: always
      on_success: change

before_install:
   - ln -s .arch.make arch.make
   linux:
      - sudo apt-get install -qq gfortran
   macosx:
      - brew install gfortran

install:
   - make

script:
   - make check
