language: Fortran

git:
   depth: 3

os:
   - linux
   - osx

matrix:
   include:
     - os: linux
       sudo: required
     - os: osx

notifications:
   email:
      recipients:
         - nickpapior@gmail.com
      on_failure: always
      on_success: change

before_install:
   - .travis/before_install.sh

install:
   - .travis/install.sh

script:
   - .travis/script.sh
