language: Fortran

os:
   - linux
     sudo: required
   - osx

notifications:
   email:
      recipients:
         - nickpapior@gmail.com
      on_failure: always
      on_success: change

before_install:
   - sudo .travis/before_install.sh

install:
   - .travis/install.sh

script:
   - .travis/script.sh
